### ISSUE TITLE
A question about training

### ISSUE THREAD

**Issue by Scxw010516** [royorel/StyleSDF#32]
Hi @royorel, 
Thank you for your great work!
I wonder what is the difference between `Training the volume renderer`  and `Training the full pipeline`？What is the latter doing more than the former?
Looking forward to your reply!

**Comment by royorel** [comment]
Hi @Scxw010516, 

The training is done in two stages. Training the volume 
renderer is the first phase of training where only the volume renderer is trained in order to generate 64x64 3D consistent faces.

In the second stage, the full pipeline (volume renderer + styleGAN generator) is trained to generate the high resolution 1024x1024 3D aware faces.

It is crucial to train the system in two stages, otherwise it won't converge.

**Comment by Scxw010516** [comment]
> Hi @Scxw010516,
> 
> The training is done in two stages. Training the volume renderer is the first phase of training where only the volume renderer is trained in order to generate 64x64 3D consistent faces.
> 
> In the second stage, the full pipeline (volume renderer + styleGAN generator) is trained to generate the high resolution 1024x1024 3D aware faces.
> 
> It is crucial to train the system in two stages, otherwise it won't converge.

Hi @royorel ,
Thank you for your prompt reply！
